name: SuperKart Project Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r "SuperKart Project/requirements.txt"
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.SUPERKART_HF_TOKEN }}
        run: python "SuperKart Project/Model_building/data_register.py"

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r "SuperKart Project/requirements.txt"
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.SUPERKART_HF_TOKEN }}
        run: python "SuperKart Project/Model_building/prep.py"

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r "SuperKart Project/requirements.txt"

      - name: Model Building
        env:
          HF_TOURISM_PACKAGE_PREDICTION_TOKEN: ${{ secrets.SUPERKART_HF_TOKEN }}
        run: python "SuperKart/Model_building/train.py"

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-training, data-prep, register-dataset]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r "SuperKart/requirements.txt"
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.SUPERKART_HF_TOKEN }}
        run: python "SuperKart/hosting/hosting.py"
